### ISSUE TITLE
Error running dev server (yarn start)

### ISSUE THREAD

**Issue by thodges-gh** [SuperblocksHQ/superblocks-lab#259]
## Environment/Browser
OS: Ubuntu 18.04.1 LTS
Browser: Firefox
NodeJS: v8.11.1
Yarn: 1.12.3

## Description
Running `yarn start` fails to run the local development server.  Also occurs when using `make`.

## Steps to reproduce
1. `yarn install`
2. `yarn start`
3. Observe error

## Expected result
Browser opens with development environment.

## Actual result
```
Starting the development server...

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/thomas/workspace/superblocks-lab/public ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/thomas/workspace/superblocks-lab/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/thomas/workspace/superblocks-lab/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/thomas/workspace/superblocks-lab/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/thomas/workspace/superblocks-lab/node_modules/chokidar/lib/nodefs-handler.js:414:19)
    at FSWatcher.<anonymous> (/home/thomas/workspace/superblocks-lab/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/home/thomas/workspace/superblocks-lab/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Reproducible
100%

**Comment by filippsen** [comment]
Hi @thodges-gh. Here is what I found out about the reported issue:

## First attempt
OS: Ubuntu 18.04.1 LTS (same)
`node --version`: v8.10.0 (similar)
`yarn --version`: 1.12.3 (same)

I was unable to reproduce the reported issue by "natural means". I also tried running multiple `yarn start` commands to see if it would get to that error, but it did not confirm on a minimal environment.

## Further inspection
`ENOSPC` is defined as "No space left on device" (See reference [1]).
If the `ENOSPC` error confirms to not be related to disk space, then it could be associated with file system settings and limits. There is one particular setting around file system event monitoring API which could be causing that behavior. Please check the following:
`cat /proc/sys/fs/inotify/max_user_watches`
It is set to `8192` by default on Debian-based systems. Reaching that limit will trigger `ENOSPC` error.

## Reproducing the problem

It is possible to experience the issue and suspect it could be related to the default configuration settings by temporarily setting the `max_user_watches` to a small value. That setting may also be different depending on the environment settings and current user preferences.

Just as an example (Warning: do not set to a smaller value, as it may end up interfering the currently running session):
`sudo sysctl fs.inotify.max_user_watches=50`

This sets the `max_user_watches` to a value way below the default one.
After that, re-running `yarn start`, then I manage to get to the same error output:
```
events.js:183
[...]
Error: watch /home/[...] ENOSPC
[...]
```
The same happens with plain `make` because it runs `yarn start` as part of the process.


## Settings and conclusion

In order to make `yarn start`, `make` and `make watch` work, temporarily set the `max_user_watches` data to a value bigger than the default one by calling: 
`sudo sysctl fs.inotify.max_user_watches=<new value>`. 
Double check by reading the data from `/proc/sys/fs/inotify/max_user_watches`.

Alternatively, set the new state as default from there on, if you are comfortable doing it, by adding the `fs.inotify.max_user_watches=<new value>` entry to `/etc/sysctl.conf` and reloading it with a subsequent `sysctl -p` call (See reference [2]).

I'm not aware of anything else that could be done for the moment, as this apparently hasn't been caught on any other distributions or environments so far.

Taking from the experiment, that setting should be sufficient. Please let me know if that is true. Thank you!

## References
[1] The Open Group Base Specifications Issue 7, 2018 edition. http://pubs.opengroup.org/onlinepubs/9699919799/
[2] sysctl(8). https://linux.die.net/man/8/sysctl

**Comment by javier-tarazaga** [comment]
Try the solution in [this stackoverflow answer](https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve/32600959#32600959)? More explanation [here](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details).
