### ISSUE TITLE
Missing ESLint rules

### ISSUE THREAD

**Issue by javier-tarazaga** [SuperblocksHQ/superblocks-lab#3]
The project is currently missing ESLint rules in order to make sure we are writing JS code in a consistent way. 

As suggestion I would simply add the aribnb rules (https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) which is a bit more picky but a great way to make sure we are writing JS following some good practices.

**Comment by filippsen** [comment]
ESLint was added to `package.json` in commit c5f631b. Along with that, a predefined ruleset is defined, as seen in: https://github.com/SuperblocksHQ/studio/blob/master/package.json#L8

It was added, but never used. My suggestion would be to start small, because a non-trivial codebase already exists.

That said, I would simply adhere to an auto-generated settings file, as recommended by the authors, and tweak it with custom and more strict variants afterwards.
Please, see #33

Thank you
