### ISSUE TITLE
After clicking the gears icon (Configuration) from the top bar, the dropdown menu stays open

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#43]
## Expected result
Expected it to close to enable editing the just opened configuration settings window.

**Comment by filippsen** [comment]
This behavior is due to `e.stopPropagation()` call written in `ProjectDialog` component `openProjectConfig` function (`src/components/topbar/index.js`).

Answering "why" it was written that way would help solving it.

**Comment by javier-tarazaga** [comment]
@filippsen this was due to the fact that the row behind the icons was clickable as well so when you clicked the icons, the event would propagate to the row and the project would be selected at the same time. A way to fix this would be to add a new container on top of the text text which cover the full width of the text container (until the icons) and add the click listener there. Something like in the drawing (the boxes represent areas and forget about the paddings, they are there just to represent the fact that there is a container behind).

**Comment by waheed25** [comment]
we can move containers upper or lower to each other with z-index but the problem is which container is on front that onClick will work if we moves dropdown icons container to front with z-index then icons onClick not works and dropdown with close because icons goes behind the container and in the current situation where we adjust the icons on front then the text containers onClick only works for text container area.

**Comment by waheed25** [comment]
yeah other thing that causing problem is **e.stopPropagation()**that is which cancels the default behaviour of the browser.

**Comment by waheed25** [comment]
Here is minor change in this branch but @filippsen please make sure it didn't produce any side effect.
https://github.com/SuperblocksHQ/studio/tree/gear-icon-issue

**Comment by filippsen** [comment]
@waheed25 Indeed it is a small change, code-wise, but I'm unfamiliar with the surroundings.
Considering that, I tested the action which involves the change in `ProjectDialog` shared in https://github.com/SuperblocksHQ/studio/tree/gear-icon-issue. 

The _Edit DApp Configuration_ window opens normally, as expected. All other buttons around it, namely _Download_ and _Delete_ are still working as intended (no interference was expected). I could not perceive any problem with this change. The change would resolve this issue.

Reading the history, the `e.stopPropagation();` line was added in commit 5efcbc3b. `git log 5efcbc3b` returns "NewDapp Dialog - Fixed clickcable area".
I don't know exactly why they were added. I can suspect the intention was exactly that, to prevent the close event when managing projects. It makes sense when downloading and removing, but nullifying action when clicking the gear icon, I find it more like an annoyance. That is the reason I brought up this idea for improvement.

I do think the proposed change suffices. Perhaps @javier could shed a light here and confirm our assumptions, just to make sure.
