### ISSUE TITLE
Dropdown buttons won't toggle on click

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#61]
## Expected result
Expected the dropdown buttons (Project list, Select an account, Select a network and Disable Web3 Accounts) to close on click when the list is already open (toggle behavior).

## Actual result
Clicking on dropdown button always open.

**Comment by waheed25** [comment]
ssuggestion in #61
https://github.com/SuperblocksHQ/studio/tree/dropDown-toggle-issue

**Comment by filippsen** [comment]
As already discussed, toggling `showMenu` apparently only works when `disableOnClickOutside` is set to `true`. Or, when removing the `handleClickOutside` property from the `Dropdown` in `src/components/dropdown/index.js`. Waheed also observed uncertain states when dealing with direct data changes.

The explanation for that is the `Dropdown` button triggers two opposite actions. First, `closeMenu`, because it was a click outside the `Dropdown`. Secondly, `showMenu`, because it was a click on the main div. It will always close then open on click, regardless of the previous state.

Commit e52a6de in `dropDown-toggle-issue`, in practice, trades off the outside click in favor of the `showMenu` toggle behavior. That would be a step back in comparison to current state.

Since I'm unfamiliar with the details of `react-onclickoutisde`, I would consider rewriting to not depend on it. At the moment, I don't have a solution for this problem, so it would be better to leave it as is (no changes).

**Comment by waheed25** [comment]
react-onclickoutisde is provide methods to handling the area either click event is occurs inside the DropDown or outSide the DropDown both of them working nice but in the scenario where click event occurs on the dropDown toggle area and dropdown is in open state then its behaviour is unNatural it closes the dropDown and opens it again but as need to have a toggle on click on the dropdown is behaviour is toggle and it return proper state value if we use disableOnClickOutside but in this case we can't close dropdown on click of outside so in short if we want toggle behaviour we need to use disableOnClickOutside otherwise we need to use some other stable package.
